# Generated by Django 2.1 on 2018-08-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainbackendapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='comment',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(verbose_name=1),
        ),
        migrations.AlterField(
            model_name='review',
            name='username',
            field=models.CharField(default='Anonymous', max_length=40),
        ),
    ]
