# Generated by Django 2.1 on 2018-08-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainbackendapp', '0003_auto_20180804_1632'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(default=4),
        ),
    ]
